DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS PremiumUser;

CREATE TABLE User (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Username TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE Post (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  AuthorId INTEGER NOT NULL,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Title TEXT NOT NULL,
  Body TEXT NOT NULL,
  FOREIGN KEY (AuthorId) REFERENCES User (Id)
);

CREATE TABLE Payment (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER NOT NULL,
  CardNumber INTEGER NOT NULL,
  Amount DECIMAL NOT NULL,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES User (Id)
);

CREATE TABLE PremiumUser (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER NOT NULL UNIQUE,
  Started TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Expires TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES User (Id)
);

